# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    

  test:
    #needs: build
    runs-on: ubuntu-latest
    services:
      selenium:
        image: elgalu/selenium
      zalenium:
        image: dosel/zalenium
        env:
          PULL_SELENIUM_IMAGE: true
          HUB_HOST: localhost
          SELENIUM_HUB_HOST: 'localhost'
        volumes: 
          - /var/run/docker.sock:/var/run/docker.sock
          - /tmp/videos:/home/seluser/videos
        ports: 
          - 4444:4444
        options: >-
          --privileged
#          --health-cmd "curl -sSL http://localhost:4444/wd/hub/status"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
        #options: --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # - name: Start up Zalenium stack
    #   working-directory: ./docker
    #   run: docker-compose up --force-recreate -d
    - name: Debugging of Zalenium
      run: curl -sSL http://localhost:4444/wd/hub/status
    #- name: Run tests
    #   working-directory: ./
      #run: ./gradlew cleanUp playground
    # - name: Kill Zalenium stack
    #   working-directory: ./docker
    #   run: docker-compose down
